package:
  name: _lightgbm_select
  version: {{ lightgbm_select_version }}

build:
  number: 2
  string: {{ build_type }}_{{ PKG_BUILDNUM }}

about:
  summary : Package used to select the specific LightGBM build variant

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

